### ISSUE TITLE
`set_thermostat` not working

### ISSUE THREAD

**Issue by OnFreund** [koreth/pycoolmasternet#1]
Hi,

It seems that `set_thermostat` does not pass on the received temperature parameter.

Thanks!

**Comment by OnFreund** [comment]
I believe that changing:

`self._make_request('temp {}')`
to:
`self._make_request('temp {} ' + str(value))`

should do the trick

**Comment by sgrimm-sg** [comment]
Thanks!

**Comment by koreth** [comment]
Whoops, managed to leave off the `str()` you suggested, which is obviously not going to work! That'll teach me to release code late at night. Real fix has been released now as version 0.0.4.
