### ISSUE TITLE
pycoolmasternet-async is missing swing functionality

### ISSUE THREAD

**Issue by amitfin** [koreth/pycoolmasternet#3]
(This is not the right repository, but the other one doesn't have "issues" enabled)

CoolMaster integration for Home Assistant doesn't support swing functionality (climate.set_swing_mode).
The integration uses the library pycoolmasternet-async which doesn't have the swing functionality, while this library does have it.
Do you know of any reason not to add it to pycoolmasternet-async, and then to the integration?
I don't mind working on these changes, but wanted to check with you first.

**Comment by Rjevski** [comment]
If this is still relevant - issues seem to be enabled on the forked repo now: https://github.com/OnFreund/pycoolmasternet-async/issues

If this is still of interest I am working on a more advanced CoolMasterNet client library and a Home Assistant custom component implementing it - while my units don't support "swing" so I can't test I've implemented this in my library.

Will update when the library & HA custom component is published.

**Comment by moosecroc** [comment]
thanks

Mick Mannion

**Comment by Rjevski** [comment]
Library is here: https://github.com/Rjevski/pycoolmasternet-ng

And HA branch is here: https://github.com/Rjevski/core/tree/coolmasternet-ng/

The CoolMaster integration in that branch has been updated so if you run this locally you can test. Alternatively, you should be able to take this entire directory: https://github.com/Rjevski/core/tree/coolmasternet-ng/homeassistant/components/coolmaster and put it in your custom_components on an existing HA installation.
